# Form implementation generated from reading ui file 'about_device.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_about_device(object):
    def setupUi(self, dialog_about_device):
        dialog_about_device.setObjectName("dialog_about_device")
        dialog_about_device.resize(561, 262)
        self.about_textBrowser = QtWidgets.QTextBrowser(parent=dialog_about_device)
        self.about_textBrowser.setGeometry(QtCore.QRect(10, 10, 541, 211))
        self.about_textBrowser.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.about_textBrowser.setObjectName("about_textBrowser")
        self.btn_exit = QtWidgets.QPushButton(parent=dialog_about_device)
        self.btn_exit.setGeometry(QtCore.QRect(10, 230, 75, 23))
        self.btn_exit.setObjectName("btn_exit")

        self.retranslateUi(dialog_about_device)
        QtCore.QMetaObject.connectSlotsByName(dialog_about_device)

    def retranslateUi(self, dialog_about_device):
        _translate = QtCore.QCoreApplication.translate
        dialog_about_device.setWindowTitle(_translate("dialog_about_device", "О приборе"))
        self.btn_exit.setText(_translate("dialog_about_device", "Закрыть"))
