# Form implementation generated from reading ui file 'auth_ok.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_auth_ok_form(object):
    def setupUi(self, auth_ok_form):
        auth_ok_form.setObjectName("auth_ok_form")
        auth_ok_form.resize(571, 138)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(auth_ok_form.sizePolicy().hasHeightForWidth())
        auth_ok_form.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(parent=auth_ok_form)
        self.label.setGeometry(QtCore.QRect(140, 20, 301, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ok_button = QtWidgets.QPushButton(parent=auth_ok_form)
        self.ok_button.setGeometry(QtCore.QRect(240, 80, 93, 28))
        self.ok_button.setObjectName("ok_button")

        self.retranslateUi(auth_ok_form)
        QtCore.QMetaObject.connectSlotsByName(auth_ok_form)

    def retranslateUi(self, auth_ok_form):
        _translate = QtCore.QCoreApplication.translate
        auth_ok_form.setWindowTitle(_translate("auth_ok_form", "Вход выполнен"))
        self.label.setText(_translate("auth_ok_form", "Вход в программу выполнен успешно."))
        self.ok_button.setText(_translate("auth_ok_form", "OK"))
