# Form implementation generated from reading ui file 'auth_error.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_auth_error_form(object):
    def setupUi(self, auth_error_form):
        auth_error_form.setObjectName("auth_error_form")
        auth_error_form.resize(571, 138)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(auth_error_form.sizePolicy().hasHeightForWidth())
        auth_error_form.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(parent=auth_error_form)
        self.label.setGeometry(QtCore.QRect(140, 10, 301, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ok_button = QtWidgets.QPushButton(parent=auth_error_form)
        self.ok_button.setGeometry(QtCore.QRect(240, 80, 93, 28))
        self.ok_button.setObjectName("ok_button")
        self.label_2 = QtWidgets.QLabel(parent=auth_error_form)
        self.label_2.setGeometry(QtCore.QRect(100, 40, 381, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(auth_error_form)
        QtCore.QMetaObject.connectSlotsByName(auth_error_form)

    def retranslateUi(self, auth_error_form):
        _translate = QtCore.QCoreApplication.translate
        auth_error_form.setWindowTitle(_translate("auth_error_form", "Ошибка авторизации"))
        self.label.setText(_translate("auth_error_form", "Данные для входа введены неверно."))
        self.ok_button.setText(_translate("auth_error_form", "OK"))
        self.label_2.setText(_translate("auth_error_form", "Проверьте праильность ввода логина и пароля."))
