# Form implementation generated from reading ui file 'guest_mode_ok.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_guest_form(object):
    def setupUi(self, guest_form):
        guest_form.setObjectName("guest_form")
        guest_form.resize(571, 217)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(guest_form.sizePolicy().hasHeightForWidth())
        guest_form.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(parent=guest_form)
        self.label.setGeometry(QtCore.QRect(190, 10, 198, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ok_button = QtWidgets.QPushButton(parent=guest_form)
        self.ok_button.setGeometry(QtCore.QRect(240, 150, 93, 28))
        self.ok_button.setObjectName("ok_button")
        self.label_2 = QtWidgets.QLabel(parent=guest_form)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 508, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=guest_form)
        self.label_3.setGeometry(QtCore.QRect(80, 70, 426, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=guest_form)
        self.label_4.setGeometry(QtCore.QRect(40, 100, 506, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(guest_form)
        QtCore.QMetaObject.connectSlotsByName(guest_form)

    def retranslateUi(self, guest_form):
        _translate = QtCore.QCoreApplication.translate
        guest_form.setWindowTitle(_translate("guest_form", "Гостевой вход"))
        self.label.setText(_translate("guest_form", "Выполнен гостевой вход."))
        self.ok_button.setText(_translate("guest_form", "OK"))
        self.label_2.setText(_translate("guest_form", "Вы не можете создавать новые карточки приборов и протоколы,"))
        self.label_3.setText(_translate("guest_form", "а так же редактировать и удалять уже существующие."))
        self.label_4.setText(_translate("guest_form", "Все остальные функции программы доступны без ограничений."))
