# Form implementation generated from reading ui file 'net_settings.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_net_settings(object):
    def setupUi(self, dialog_net_settings):
        dialog_net_settings.setObjectName("dialog_net_settings")
        dialog_net_settings.resize(318, 185)
        self.label = QtWidgets.QLabel(parent=dialog_net_settings)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=dialog_net_settings)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=dialog_net_settings)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_3.setObjectName("label_3")
        self.ip_addr_edit = QtWidgets.QLineEdit(parent=dialog_net_settings)
        self.ip_addr_edit.setGeometry(QtCore.QRect(160, 20, 141, 20))
        self.ip_addr_edit.setObjectName("ip_addr_edit")
        self.mask_edit = QtWidgets.QLineEdit(parent=dialog_net_settings)
        self.mask_edit.setGeometry(QtCore.QRect(160, 50, 141, 20))
        self.mask_edit.setObjectName("mask_edit")
        self.port_edit = QtWidgets.QLineEdit(parent=dialog_net_settings)
        self.port_edit.setGeometry(QtCore.QRect(160, 80, 71, 20))
        self.port_edit.setObjectName("port_edit")
        self.btn_save_data = QtWidgets.QPushButton(parent=dialog_net_settings)
        self.btn_save_data.setGeometry(QtCore.QRect(80, 130, 75, 23))
        self.btn_save_data.setObjectName("btn_save_data")
        self.btn_exit = QtWidgets.QPushButton(parent=dialog_net_settings)
        self.btn_exit.setGeometry(QtCore.QRect(170, 130, 75, 23))
        self.btn_exit.setObjectName("btn_exit")

        self.retranslateUi(dialog_net_settings)
        QtCore.QMetaObject.connectSlotsByName(dialog_net_settings)

    def retranslateUi(self, dialog_net_settings):
        _translate = QtCore.QCoreApplication.translate
        dialog_net_settings.setWindowTitle(_translate("dialog_net_settings", "Сетевые настройки"))
        self.label.setText(_translate("dialog_net_settings", "IP адрес:"))
        self.label_2.setText(_translate("dialog_net_settings", "Маска подсети:"))
        self.label_3.setText(_translate("dialog_net_settings", "Порт:"))
        self.btn_save_data.setText(_translate("dialog_net_settings", "Сохранить"))
        self.btn_exit.setText(_translate("dialog_net_settings", "Отмена"))
