# Form implementation generated from reading ui file 'protocol_view.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_diaog_viewer(object):
    def setupUi(self, diaog_viewer):
        diaog_viewer.setObjectName("diaog_viewer")
        diaog_viewer.resize(1072, 590)
        self.table_protocol = QtWidgets.QTableWidget(parent=diaog_viewer)
        self.table_protocol.setGeometry(QtCore.QRect(10, 10, 1051, 521))
        self.table_protocol.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_protocol.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_protocol.setRowCount(1)
        self.table_protocol.setColumnCount(3)
        self.table_protocol.setObjectName("table_protocol")
        self.table_protocol.horizontalHeader().setDefaultSectionSize(343)
        self.table_protocol.horizontalHeader().setMinimumSectionSize(49)
        self.btn_exit = QtWidgets.QPushButton(parent=diaog_viewer)
        self.btn_exit.setGeometry(QtCore.QRect(10, 540, 151, 28))
        self.btn_exit.setObjectName("btn_exit")

        self.retranslateUi(diaog_viewer)
        QtCore.QMetaObject.connectSlotsByName(diaog_viewer)

    def retranslateUi(self, diaog_viewer):
        _translate = QtCore.QCoreApplication.translate
        diaog_viewer.setWindowTitle(_translate("diaog_viewer", "Обозреватель протокола"))
        self.btn_exit.setText(_translate("diaog_viewer", "Закрыть"))
