# Form implementation generated from reading ui file 'protocol.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_diaog_protocol_redactor(object):
    def setupUi(self, diaog_protocol_redactor):
        diaog_protocol_redactor.setObjectName("diaog_protocol_redactor")
        diaog_protocol_redactor.resize(1072, 590)
        self.table_protocol = QtWidgets.QTableWidget(parent=diaog_protocol_redactor)
        self.table_protocol.setGeometry(QtCore.QRect(10, 10, 1051, 271))
        self.table_protocol.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_protocol.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_protocol.setRowCount(1)
        self.table_protocol.setColumnCount(3)
        self.table_protocol.setObjectName("table_protocol")
        self.table_protocol.horizontalHeader().setDefaultSectionSize(343)
        self.table_protocol.horizontalHeader().setMinimumSectionSize(49)
        self.label = QtWidgets.QLabel(parent=diaog_protocol_redactor)
        self.label.setGeometry(QtCore.QRect(10, 300, 251, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_name = QtWidgets.QLineEdit(parent=diaog_protocol_redactor)
        self.line_name.setGeometry(QtCore.QRect(10, 330, 251, 22))
        self.line_name.setObjectName("line_name")
        self.label_2 = QtWidgets.QLabel(parent=diaog_protocol_redactor)
        self.label_2.setGeometry(QtCore.QRect(10, 370, 681, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_request = QtWidgets.QLineEdit(parent=diaog_protocol_redactor)
        self.line_request.setGeometry(QtCore.QRect(10, 400, 681, 22))
        self.line_request.setObjectName("line_request")
        self.label_3 = QtWidgets.QLabel(parent=diaog_protocol_redactor)
        self.label_3.setGeometry(QtCore.QRect(10, 440, 681, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_answer = QtWidgets.QLineEdit(parent=diaog_protocol_redactor)
        self.line_answer.setGeometry(QtCore.QRect(10, 470, 681, 22))
        self.line_answer.setObjectName("line_answer")
        self.checkBox_no_answer = QtWidgets.QCheckBox(parent=diaog_protocol_redactor)
        self.checkBox_no_answer.setGeometry(QtCore.QRect(720, 470, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_no_answer.setFont(font)
        self.checkBox_no_answer.setObjectName("checkBox_no_answer")
        self.btn_save_command = QtWidgets.QPushButton(parent=diaog_protocol_redactor)
        self.btn_save_command.setGeometry(QtCore.QRect(10, 540, 151, 28))
        self.btn_save_command.setObjectName("btn_save_command")
        self.line = QtWidgets.QFrame(parent=diaog_protocol_redactor)
        self.line.setGeometry(QtCore.QRect(10, 510, 1051, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.btn_delete_command = QtWidgets.QPushButton(parent=diaog_protocol_redactor)
        self.btn_delete_command.setGeometry(QtCore.QRect(180, 540, 151, 28))
        self.btn_delete_command.setObjectName("btn_delete_command")

        self.retranslateUi(diaog_protocol_redactor)
        QtCore.QMetaObject.connectSlotsByName(diaog_protocol_redactor)

    def retranslateUi(self, diaog_protocol_redactor):
        _translate = QtCore.QCoreApplication.translate
        diaog_protocol_redactor.setWindowTitle(_translate("diaog_protocol_redactor", "Dialog"))
        self.label.setText(_translate("diaog_protocol_redactor", "Введите название команды:"))
        self.label_2.setText(_translate("diaog_protocol_redactor", "Введите запрос в шестнадцатеричном формате, используя символ \"/\" в качестве разделителя:"))
        self.label_3.setText(_translate("diaog_protocol_redactor", "Введите ответ в шестнадцатеричном формате, используя символ \"/\" в качестве разделителя:"))
        self.checkBox_no_answer.setText(_translate("diaog_protocol_redactor", "Нет ответа"))
        self.btn_save_command.setText(_translate("diaog_protocol_redactor", "Сохранить команду"))
        self.btn_delete_command.setText(_translate("diaog_protocol_redactor", "Удалить команду"))
