# Form implementation generated from reading ui file 'redactor.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Redactor(object):
    def setupUi(self, Redactor):
        Redactor.setObjectName("Redactor")
        Redactor.resize(800, 445)
        self.centralwidget = QtWidgets.QWidget(parent=Redactor)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 10, 331, 17))
        self.checkBox.setObjectName("checkBox")
        self.btn_about_device = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_about_device.setGeometry(QtCore.QRect(10, 370, 75, 23))
        self.btn_about_device.setObjectName("btn_about_device")
        self.table_device = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_device.setGeometry(QtCore.QRect(10, 40, 781, 321))
        self.table_device.setObjectName("table_device")
        self.table_device.setColumnCount(0)
        self.table_device.setRowCount(0)
        Redactor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Redactor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_2.setObjectName("menu_2")
        Redactor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Redactor)
        self.statusbar.setObjectName("statusbar")
        Redactor.setStatusBar(self.statusbar)
        self.edit_device_card = QtGui.QAction(parent=Redactor)
        self.edit_device_card.setObjectName("edit_device_card")
        self.edit_net_settings = QtGui.QAction(parent=Redactor)
        self.edit_net_settings.setObjectName("edit_net_settings")
        self.edit_protocol = QtGui.QAction(parent=Redactor)
        self.edit_protocol.setObjectName("edit_protocol")
        self.create_device_card = QtGui.QAction(parent=Redactor)
        self.create_device_card.setObjectName("create_device_card")
        self.create_net_settings = QtGui.QAction(parent=Redactor)
        self.create_net_settings.setObjectName("create_net_settings")
        self.create_protocol = QtGui.QAction(parent=Redactor)
        self.create_protocol.setObjectName("create_protocol")
        self.menu.addAction(self.edit_device_card)
        self.menu.addAction(self.edit_net_settings)
        self.menu.addAction(self.edit_protocol)
        self.menu_2.addAction(self.create_device_card)
        self.menu_2.addAction(self.create_net_settings)
        self.menu_2.addAction(self.create_protocol)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(Redactor)
        QtCore.QMetaObject.connectSlotsByName(Redactor)

    def retranslateUi(self, Redactor):
        _translate = QtCore.QCoreApplication.translate
        Redactor.setWindowTitle(_translate("Redactor", "Секвенсер - Редактор"))
        self.checkBox.setText(_translate("Redactor", "Показывать приборы, созданные другими пользователями"))
        self.btn_about_device.setText(_translate("Redactor", "Подробнее"))
        self.menu.setTitle(_translate("Redactor", "Редактировать"))
        self.menu_2.setTitle(_translate("Redactor", "Создать"))
        self.edit_device_card.setText(_translate("Redactor", "Карточка прибора"))
        self.edit_net_settings.setText(_translate("Redactor", "Сетевые настройки"))
        self.edit_protocol.setText(_translate("Redactor", "Протокол обмена"))
        self.create_device_card.setText(_translate("Redactor", "Карточка прибора"))
        self.create_net_settings.setText(_translate("Redactor", "Сетевые настройки"))
        self.create_protocol.setText(_translate("Redactor", "Протокол обмена"))
