# Form implementation generated from reading ui file 'sequencer_settings.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(727, 391)
        self.tabWidget = QtWidgets.QTabWidget(parent=Settings)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 701, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_test = QtWidgets.QWidget()
        self.tab_test.setObjectName("tab_test")
        self.label = QtWidgets.QLabel(parent=self.tab_test)
        self.label.setGeometry(QtCore.QRect(10, 30, 341, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(parent=self.tab_test)
        self.spinBox.setGeometry(QtCore.QRect(390, 30, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(parent=self.tab_test)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 341, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtWidgets.QSpinBox(parent=self.tab_test)
        self.spinBox_2.setGeometry(QtCore.QRect(390, 80, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.tab_test)
        self.checkBox.setGeometry(QtCore.QRect(10, 130, 421, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.tab_test, "")
        self.tab_connect = QtWidgets.QWidget()
        self.tab_connect.setObjectName("tab_connect")
        self.tabWidget.addTab(self.tab_connect, "")

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Секвенсер - настройки"))
        self.label.setText(_translate("Settings", "Время ожидания ответа (секунд):"))
        self.label_2.setText(_translate("Settings", "Время паузы между отправкой команд (секунд):"))
        self.checkBox.setText(_translate("Settings", "Остановить тест, если истекло время ожидания"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_test), _translate("Settings", "Тестирование"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_connect), _translate("Settings", "Обмен данными"))
