# Form implementation generated from reading ui file 'sequencer_new_card.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_create_card_dialog(object):
    def setupUi(self, create_card_dialog):
        create_card_dialog.setObjectName("create_card_dialog")
        create_card_dialog.resize(468, 542)
        self.name_line = QtWidgets.QLabel(parent=create_card_dialog)
        self.name_line.setGeometry(QtCore.QRect(20, 20, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.name_line.setFont(font)
        self.name_line.setObjectName("name_line")
        self.lineEdit = QtWidgets.QLineEdit(parent=create_card_dialog)
        self.lineEdit.setGeometry(QtCore.QRect(240, 20, 211, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=create_card_dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_serial_num = QtWidgets.QLineEdit(parent=create_card_dialog)
        self.line_serial_num.setGeometry(QtCore.QRect(240, 60, 211, 22))
        self.line_serial_num.setObjectName("line_serial_num")
        self.label_2 = QtWidgets.QLabel(parent=create_card_dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_engineer = QtWidgets.QLineEdit(parent=create_card_dialog)
        self.line_engineer.setGeometry(QtCore.QRect(240, 100, 211, 22))
        self.line_engineer.setObjectName("line_engineer")
        self.label_3 = QtWidgets.QLabel(parent=create_card_dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_programmer = QtWidgets.QLineEdit(parent=create_card_dialog)
        self.line_programmer.setGeometry(QtCore.QRect(240, 140, 211, 22))
        self.line_programmer.setObjectName("line_programmer")
        self.label_4 = QtWidgets.QLabel(parent=create_card_dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=create_card_dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(240, 180, 211, 141))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(create_card_dialog)
        QtCore.QMetaObject.connectSlotsByName(create_card_dialog)

    def retranslateUi(self, create_card_dialog):
        _translate = QtCore.QCoreApplication.translate
        create_card_dialog.setWindowTitle(_translate("create_card_dialog", "Новая карточка"))
        self.name_line.setText(_translate("create_card_dialog", "Название прибора:"))
        self.label.setText(_translate("create_card_dialog", "Серийный номер:"))
        self.label_2.setText(_translate("create_card_dialog", "Разработчик:"))
        self.label_3.setText(_translate("create_card_dialog", "Программист ВПО:"))
        self.label_4.setText(_translate("create_card_dialog", "Описание:"))
